export const GET_CATEGORY_PRODUCTS = 'CATEGORY/GET_PRODUCTS'
export const SWITCH_PRODUCTS_DISPLAY_TYPE = 'CATEGORY/SWITCH_PRODUCTS_DISPLAY_TYPE'
export const SWITCH_PRODUCTS_SORT_TYPE = 'CATEGORY/SWITCH_PRODUCTS_SORT_TYPE'
export const UPDATE_PRODUCT_AMOUNT = 'CATEGORY/UPDATE_PRODUCT_AMOUNT'


export const ADD_CART_PRODUCT = 'CART/ADD_PRODUCT'
export const REMOVE_CART_PRODUCT = 'CART/REMOVE_PRODUCT'
export const CLEAR_CART = 'CART/CLEAR'

export const ADD_WISHLIST_PRODUCT = 'WISHLIST/ADD_PRODUCT'
export const REMOVE_WISHLIST_PRODUCT = 'WISHLIST/REMOVE_PRODUCT'
export const CLEAR_WISHLIST = 'WISHLIST/CLEAR'

