export const GET_CATEGORY_PRODUCTS = 'CATEGORY/GET_PRODUCTS'
export const SWITCH_PRODUCTS_DISPLAY_TYPE = 'CATEGORY/SWITCH_PRODUCTS_DISPLAY_TYPE'
export const SWITCH_PRODUCTS_SORT_TYPE = 'CATEGORY/SWITCH_PRODUCTS_SORT_TYPE'

export const GET_CART_PRODUCTS = 'CART/GET_PRODUCTS'
